name: proteogan
channels:
  - defaults
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - tensorflow-gpu=2.0
  - pandas
  - numpy
  - matplotlib
  - goatools
  - seaborn
  - scikit-learn
  - tqdm
